version: '2'
services:
  worker:
    build: ./reddit_worker
    env_file:
     - mongo_config.env
    environment:
     - MONGO_HOST=db
     - EXTERNAL_TEST=${EXTERNAL_TEST}
    depends_on:
     - db
  api:
    build: ./history_api
    env_file:
     - mongo_config.env
    environment:
     - MONGO_HOST=db
    ports:
     - "5000:5000"
    depends_on:
     - db
  db:
    image: mongo:3.2
