app:
  subreddits:
    - python
    - javascript
  reddit_user_agent: reddit-feed-py (by /u/zaboco)
  pooling_interval: 60

mongo:
  host: localhost
  port: 27017
  database: reddit_history
  collection: items
